// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsSqlDom")>]
[<assembly: AssemblyProductAttribute("FsSqlDom")>]
[<assembly: AssemblyDescriptionAttribute("F# helper for SQL parsing")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsSqlDom"
    let [<Literal>] AssemblyProduct = "FsSqlDom"
    let [<Literal>] AssemblyDescription = "F# helper for SQL parsing"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
