// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsSqlDom")>]
[<assembly: AssemblyProductAttribute("FsSqlDom")>]
[<assembly: AssemblyDescriptionAttribute("F# helper for SQL parsing")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsSqlDom"
    let [<Literal>] AssemblyProduct = "FsSqlDom"
    let [<Literal>] AssemblyDescription = "F# helper for SQL parsing"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
